import re
import csv

INPUT = "headlines_raw.csv"
OUTPUT = "headlines_with_niches.csv"

# Auto rules
RULES = {
    "automotive": [
        " car ",
        " cars ",
        " suv ",
        " suvs ",
        " crossover ",
        " truck ",
        " trucks ",
        " vehicle ",
        " vehicles ",
        " tyre ",
        " tire ",
        " tires ",
        " cuv ",
        " pickup ",
        " motorhome ",
        " rv ",
        " camper ",
        " motorhome ",
        " financing ",
        " motorcycle financing ",
        " tires ",
        " toyota ",
        " honda ",
        " ford ",
        " chevy ",
        " chevrolet ",
        " nissan ",
        " jeep ",
        " kia ",
        " subaru ",
        " lexus ",
        " buick ",
        " ram ",
        " dodge ",
        " tacoma ",
        " wrangler ",
        " rav4 ",
        " grand cherokee ",
        " silverado ",
        " tahoe ",
        " explorer ",
        " accord ",
        " altima ",
        " frontier ",
        " telluride ",
        " envoy ",
        " montana ",
        " nautlius ",
        " nautilus ",
        " terra ",
        " crosstrek ",
        " prado ",
        " highlander ",
        " kluger ",
        " picanto ",
        " f-150 ",
        " f 150 ",
        " f-450 ",
        " f 450 ",
        " ranger ",
        " tacozilla ",
        " colorado ",
        " armada ",
        " police impound cars ",
        " police auction cars ",
        " seized cars ",
        " police impound boats ",
        " dollar-cost averaging ",
        " hyundai h350 ",
        " hyundai palisade ",
        " hyundai porter ",
        " hyundai bayon ",
        " hyundai tucson ",
        " cadillac ct4 ",
        " mazda cx-70 ",
        " mazda cx 70 ",
        " bmw x5 ",
        " automotive superchargers ",
        " hydrogen fuel cells in the automotive world ",
        " automotive color science ",
        " continuously variable transmission ",
        " cvt transmission ",
        " performance tuning ",
        " future of transportation ",
        " automotive innovation ",
        " automotive technology ",
        " automotive innovations reshaping the future ",
        " airship industry ",
        " pay monthly wheels "
    ],

    "health_medical": [
        " health ",
        " healthcare ",
        " medical ",
        " medicine ",
        " hospital ",
        " clinic ",
        " doctor ",
        " physician ",
        " nurse ",
        " dementia ",
        " autism ",
        " asthma ",
        " glaucoma ",
        " lung cancer ",
        " heart failure ",
        " nafld ",
        " nash ",
        " pulmonary hypertension ",
        " plaque psoriasis ",
        " actinic keratosis ",
        " obesity ",
        " osteoarthritis ",
        " osteoporosis ",
        " angioedema ",
        " choledocholithiasis ",
        " cholangitis ",
        " amyloidosis ",
        " sma ",
        " multiple sclerosis ",
        " cancer ",
        " tumor ",
        " tumours ",
        " dentures ",
        " invisible dentures ",
        " tooth replacement ",
        " dental implants ",
        " screwless implants ",
        " dental clips ",
        " cosmetic dentistry ",
        " blepharitis ",
        " demodex ",
        " eyelash mites ",
        " incontinence ",
        " neuropathy ",
        " sciatica ",
        " arthritis clinic ",
        " arthritis clinics ",
        " antidepressants ",
        " depression ",
        " brain power test ",
        " glaucoma specialists ",
        " ophthalmology ",
        " supplements for men 50+ ",
        " multivitamin ",
        " healthy ageing ",
        " laser fat removal ",
        " non-surgical fat removal ",
        " tummy tuck ",
        " abdominoplasty ",
        " ed treatment ",
        " erectile dysfunction ",
        " probiotics ",
        " adaptogens ",
        " tinnitus ",
        " sleep apnea ",
        " cpap ",
        " clinical trial ",
        " clinical trials ",
        " tetanus toxoid ",
        " urinary tract infections ",
        " uti ",
        " bile duct stone ",
        " bile duct stones ",
        " weight loss options ",
        " weight loss tips ",
        " ulcerative colitis ",
        " ibs ",
        " irritable bowel syndrome ",
        " atopic dermatitis ",
        " dermatitis ",
        " psoriasis ",
        " psoriatic arthritis ",
        " copd ",
        " chronic obstructive pulmonary disease ",
        " chronic kidney disease ",
        " kidney disease ",
        " fatty liver ",
        " nonalcoholic fatty liver ",
        " nonalcoholic steatohepatitis ",
        " migraine ",
        " migraines ",
        " lymphoma ",
        " stomach cancer ",
        " colonoscopy ",
        " cancer screenings ",
        " alzheimer ",
        " hiv treatment ",
        " glucose monitoring ",
        " continuous glucose monitor ",
        " cgm ",
        " diabetes care ",
        " diabetic ",
        " hearing aids ",
        " hearing aid ",
        " dry eye ",
        " cataract surgery ",
        " eczema ",
        " sperm donation ",
        " semen donation ",
        " egg donation ",
        " donation clinics ",
        " weight loss treatments ",
        " gastric balloon ",
        " knee pain ",
        " ulcerative colitis treatments ",
        " ibd treatments "
        " epilepsy medications ",
        " epilepsy medication ",
        " epilepsy treatments ",
        " inpatient rehab centers ",
        " inpatient rehab ",
        " rehab centers ",
        " rehab in the u.s. ",
        " vaginal itching ",
        " breast lift surgery ",
        " breast lift ",
        " non-verbal learning disorder ",
        " nvld ",
        " bone strength ",
        " bone strength foods ",
        " laser eye surgery ",
        " echocardiogram ",
        " echocardiogram procedure ",
        " radiation therapy ",
        " radiation therapy explained ",
        " dental implant price ",
        " dental implant costs ",
        " affordable dental implants ",
        " dental implant solutions ",
        " ctcl treatment ",
        " hiv symptoms ",
        " hiv treatments ",
        " hiv treatment developments ",
        " diabetes trials ",
        " diabetes trial ",
        " glucose monitors ",
        " needle-free glucose monitors ",
        " aortic valve conditions ",
        " rrms treatment ",
        " iga nephropathy ",
        " nephropathy treatment ",
        " adhd diagnosis ",
        " online adhd diagnosis ",
        " online adhd treatments ",
        " nursing programs ",
        " nursing industry ",
        " nutrition programs ",
        " podiatry foot care ",
        " ostomy pillow ",
        " gallstone removal ",
        " gallbladder surgery risks ",
        " macular degeneration ",
        " age-related macular degeneration ",
        " hearing loss prevention ",
        " preserve your hearing ",
        " heart performance ",
        " heart performance tips ",
        " quit smoking ",
        " evidence-based strategies to quit ",
        " bed bug removal guide "
        " prescription ",
        " medication ",
        " medicine ",
        " hepatitus ",
        " prep ",
        " epilepsy medications ",
        " epilepsy medication side effects ",
        " laser skin treatment ",
        " laser skin treatments ",
        " epidermolysis bullosa treatment ",
        " parkinson’s disease treatments ",
        " polymyalgia rheumatica ",
        " swollen ankles treatment ",
        " rehab in the u.s. ",
        " rehab care options ",
        " adhd management ",
        " adhd management through online diagnosis ",
        " online adhd diagnosis ",
        " same-day adhd scripts ",
        " adhd prescriptions with telehealth ",
        " preserving your hearing ",
        " improve your heart's performance ",
        " heart performance strategies ",
        " dental care tips for retirees ",
        " male circulation support ",
        " circulation support tools ",
        " weight management habits ",
        " nasal polyps prevention ",
        " recurring gallstones ",
        " rheumatoid arthritis pain alternatives ",
        " rheumatoid arthritis care strategies ",
        " spinal muscular atrophy signs ",
        " hiv treatment guide ",
        " phentermine and weight loss ",
        " natural approaches to lower blood sugar ",
        " bed bugs natural methods ",
        " parkinson’s ",
        " parkinsons disease treatments ",
        " swollen ankles treatment ",
        " management and treatment tips ",
        " gallstone risks after gallbladder surgery ",
        " gallstone risks ",
        " rehab in the u.s. ",
        " rehab care options ",
        " adhd scripts ",
        " same-day adhd scripts ",
        " online adhd scripts ",
        " adhd online diagnosis ",
        " nasal polyps prevention ",
        " hepatitis cases detected today ",
        " spinal muscular atrophy signs ",
        " heart performance ",
        " improve your heart's performance ",
        " stem cells for arthritis ",
        " arthritis clinic selection ",
        " antidepressant options for older adults ",
        " hiv treatment guide ",
        " portable oxygen concentrators ",
        " weight loss foods 2025 ",
        " phentermine explained ",
        " bed bugs natural methods ",
        " non-surgical fat removal ",
        " abdominal fat removal without surgery ",
        " laser lidstraffung ",
        " laser eye surgery right for me "
    ],

    "sexual_health": [
        " erectile dysfunction ",
        " ed treatment ",
        " ed solutions ",
        " prostate health ",
        " what really works for ed ",
        " ed in 2025 ",
        " male circulation support tools ",
        " stubborn belly fat ",
        " belly fat removal ",
        " non-surgical fat removal ",
        " laser hair removal ",
        " non-surgical facelift alternatives "
    ],

    "housing_property": [
        " abandoned houses ",
        " foreclosed homes ",
        " foreclosures ",
        " bank-owned ",
        " police impound boats ",
        " rent-to-own ",
        " rent to own ",
        " rent-to-buy ",
        " rent to buy ",
        " social housing ",
        " section 8 ",
        " section 202 ",
        " apartments for seniors ",
        " retirement bungalows ",
        " mobile homes ",
        " modular homes ",
        " container homes ",
        " prefabricated homes ",
        " pre-fab homes ",
        " granny annexes ",
        " accessory dwelling ",
        " backyard apartment ",
        " home value ",
        " property value ",
        " property values ",
        " house value ",
        " homeownership ",
        " down payment ",
        " cabins ",
        " mountain cabins ",
        " blue ridge cabins ",
        " property prices ",
        " home prices ",
        " us home values ",
        " apartments for rent ",
        " apartment for rent ",
        " no deposit apartments ",
        " no-deposit apartments ",
        " one bedroom apartments ",
        " 1 bedroom apartments ",
        " senior apartments ",
        " senior housing ",
        " container housing ",
        " prefabricated housing ",
        " prefab housing ",
        " pre fab cabins ",
        " prefab cabins ",
        " delivered cabins ",
        " new construction homes ",
        " affordable housing "
        " home ",
        " solar ",
        " hidden costs of home ownership ",
        " value of your home is publicly available ",
        " real value of your home ",
        " home could truly be worth ",
        " where your home really stands in the market ",
        " approximate value with an online estimator ",
        " current u.s. real estate market ",
        " current trends in us real estate market ",
        " revitalizing historical buildings ",
        " apartments without a deposit ",
        " affordable housing options near expensive campuses ",
        " backyard pool innovations ",
        " affordable living options in northeast houston ",
        " buy a home in florida by 2025 ",
        " california's 2025 housing market ",
        " see what your home might be worth today ",
        " home could truly be worth ",
        " approximate value of your home ",
        " hidden potential value of your property ",
        " where your home really stands in the market ",
        " current u.s. real estate market ",
        " trends in us real estate market ",
        " real estate investing in emerging markets ",
        " luxury real estate investments ",
        " florida housing market 2025 ",
        " california housing market 2025 ",
        " affordable apartments in a competitive market ",
        " apartments without a deposit ",
        " local real estate listings ",
        " off-market real estate deals ",
        " rundown properties strategic approach "
    ],

    "supplements_wellness": [
        " supplements ",
        " multivitamin ",
        " vitamins ",
        " wellness ",
        " wellness programs ",
        " lifestyle programs ",
        " healthy lifestyle ",
        " fitness ",
        " gym shoes ",
        " strength training ",
        " tai chi ",
        " yoga ",
        " meditation ",
        " breathwork ",
        " sleep masks ",
        " sleep chairs ",
        " bedtime drinks ",
        " wellness gadgets ",
        " spa ",
        " body spa ",
        " sound therapy ",
        " hot girl walk ",
        " mindfulness ",
        " mental wellness ",
        " resilience ",
        " anxiety management ",
        " anxiety tips ",
        " mental clarity ",
        " brain potential ",
        " hydration tracking ",
        " weight management "
        " superfoods ",
        " superfood hype ",
        " hearing preservation ",
        " heart performance support ",
        " knee comfort vitamins ",
        " nutritional support for knee ",
        " healthy living ",
        " quick dinner recipes ",
        " healthy alternatives ",
        " snack smarter ",
        " movement without gym ",
        " reducing sugar ",
        " lifestyle programs ",
        " sustainable lifestyle ",
        " superfoods worth the hype ",
        " truth about superfoods ",
        " weight management habits ",
        " healthy living tips ",
        " exercise tips ",
        " movement without going to the gym ",
        " quick dinner recipes that are healthy ",
        " healthy alternatives that do not taste like cardboard ",
        " more fiber in your daily diet ",
        " more vegetables in your diet ",
        " oatmeal more tasty ",
        " balanced diet enhances longevity ",
        " lifestyle changes for longevity ",
        " superfoods worth the hype ",
        " trending foods that promote weight loss ",
        " healthy living habits ",
        " smart ways to budget without feeling deprived ",
        " movement without going to the gym ",
        " quick dinner recipes that are healthy ",
        " healthy snack alternatives ",
        " hydration and nutrition tracking tips ",
        " weight management habits to know ",
        " lifestyle for longevity ",
        " at-home massage services ",
        " in-house massage services ",
        " in-home massage services ",
        " full body massage guide ",
        " russian full body massage ",
        " spa massage at home ",
        " babysitter service ",
        " find more babysitter service ",
        " room heaters cozy and safe warming ",
        " portable oxygen concentrators easier breathing ",
        " walk-in bathtubs safest way to bathe ",
        " smart recliners ",
        " massage chair deals ",
        " sleep chair or recliner "
    ],

    "senior_living_mobility": [
        " seniors ",
        " over 50 ",
        " over 60 ",
        " 55+ ",
        " senior-friendly ",
        " senior housing ",
        " senior homes ",
        " senior home ",
        " senior apartments ",
        " senior living ",
        " retirement bungalows ",
        " retirement destinations ",
        " retirement villages ",
        " retirement village ",
        " retirement home ",
        " retirement homes ",
        " retirement communities ",
        " utilities-included apartments for seniors ",
        " assisted living ",
        " dementia care facilities ",
        " care home ",
        " care homes ",
        " nursing home ",
        " nursing homes ",
        " in home care ",
        " in-home care ",
        " home care ",
        " in-home caretakers ",
        " senior day care ",
        " senior day center ",
        " portable stairlifts ",
        " mobile stairlifts ",
        " stairlift ",
        " stair lift ",
        " mobility scooters ",
        " scooters ",
        " mobility aids ",
        " mobility equipment ",
        " medicare ",
        " medicaid ",
        " centrelink ",
        " superannuation ",
        " senior travel ",
        " solo senior travel ",
        " senior discounts ",
        " senior internet "
        " senior cruise discounts ",
        " senior cruises ",
        " last-minute senior cruise ",
        " 55+ travelers ",
        " in-home caretakers ",
        " in home caretakers ",
        " affordable in-home care ",
        " aging parents ",
        " aging parents need ",
        " senior phones ",
        " senior-friendly phones ",
        " stair lifts ",
        " portable stair lifts ",
        " home mobility ",
        " senior-friendly furniture ",
        " senior friendly furniture ",
        " senior-friendly dental care ",
        " 2-bed senior houses ",
        " senior houses designed for accessibility ",
        " 55+ cottages ",
        " senior residences ",
        " improving senior mobility ",
        " practical solutions for senior mobility ",
        " senior fraud prevention ",
        " tips to prevent senior fraud ",
        " senior-friendly dental care ",
        " senior women outfits ",
        " sheath comfortable outfits for senior women ",
        " in-home caretakers ",
        " affordable in-home caretakers ",
        " prevent senior fraud ",
        " security tips for seniors ",
        " senior fraud prevention ",
        " senior-friendly dental care ",
        " dentists for seniors ",
        " senior phones near you ",
        " portable stair lifts ",
        " stair lifts safe home mobility ",
        " 2-bed senior houses ",
        " 55+ cottages ",
        " senior residences independent living "
    ],

    "insurance": [
        " insurance ",
        " life ",
        " fire ",
        " term ",
    ],

    "finance_investing": [
        " cd rates ",
        " cd rate ",
        " 6-month cd ",
        " income ",
        " high-interest savings ",
        " high-yield savings ",
        " high yield savings ",
        " savings accounts ",
        " savings apps ",
        " money saving apps ",
        " checking account bonuses ",
        " bank bonuses ",
        " bank account bonus ",
        " checking account ",
        " online bank ",
        " cash rewards ",
        " invest ",
        " inveting ",
        " retire ",
        " retirement ",
        " tax advantaged ",
        " tax efficient ",
        " etf ",
        " etfs ",
        " mutual funds ",
        " index funds ",
        " dividend investing ",
        " blue chip stocks ",
        " compound interest ",
        " dollar-cost averaging ",
        " gold ira ",
        " gold iras ",
        " ira kits ",
        " passive income ",
        " financial independence ",
        " retirement planning ",
        " retirement plan ",
        " pension ",
        " state pension ",
        " home equity ",
        " home equity loan ",
        " reverse mortgage ",
        " home equity release ",
        " equity release ",
        " mortgage ",
        " loan ",
        " fha loan ",
        " fha loans ",
        " government assisted home loans ",
        " government-assisted home loans ",
        " government assisted loans ",
        " va loans ",
        " va loan ",
        " va benefits ",
        " veterans benefits ",
        " disability compensation ",
        " disability grants ",
        " personal loans ",
        " student loans ",
        " parent loans ",
        " emergency cash ",
        " instant loans ",
        " fast loans ",
        " quick cash loans ",
        " loan options ",
        " credit cards ",
        " balance transfer ",
        " instant approval credit cards ",
        " cash back card ",
        " cashback credit card ",
        " credit score ",
        " bad credit ",
        " no credit ",
        " no credit checks ",
        " no deposit ",
        " no down payment ",
        " cash now pay later ",
        " buy now pay later ",
        " prepaid debit cards ",
        " debit cards ",
        " credit ",
        " grants ",
        " scholarships ",
        " small farms grants ",
        " financial aid ",
        " government grants ",
        " grant opportunities ",
        " utilities assistance ",
        " energy assistance ",
        " tax prep services ",
        " tax preparation services ",
        " tax preparation ",
        " tax prep services ",
        " irs debt ",
        " insurance quotes ",
        " pet insurance ",
        " dog insurance ",
        " auto insurance ",
        " car insurance ",
        " home insurance ",
        " homeowners insurance ",
        " home insurance quotes ",
        " renter insurance ",
        " renters insurance ",
        " vision insurance ",
        " life insurance ",
        " home insurance quotes ",
        " mortgage refinancing ",
        " debt relief ",
        " debt forgiveness ",
        " budgeting ",
        " financial scams "
        " business loans ",
        " small business loans ",
        " easy loans ",
        " loan options ",
        " lines of credit ",
        " line of credit ",
        " direct deposit loans ",
        " fast cash loans ",
        " cash loans ",
        " equity loans ",
        " home equity loans ",
        " abandoned property investment ",
        " single-family rental ",
        " single family rental ",
        " rental investments ",
        " real estate investing ",
        " commercial real estate ",
        " off-market real estate ",
        " off market real estate ",
        " real estate wholesaling ",
        " reits ",
        " real estate investment trusts ",
        " gold investing ",
        " gold investment ",
        " investment strategies ",
        " sustainable investments ",
        " crypto investing ",
        " cryptocurrency investing ",
        " credit counseling ",
        " credit counseling services ",
        " high-interest savings ",
        " high interest savings ",
        " savings options ",
        " bank account offers ",
        " cashback cards ",
        " cashback cards ",
        " credit card comparison ",
        " financial protection programs ",
        " digital banking ",
        " start digital banking ",
        " financial hurdles ",
        " financial green flags ",
        " sustainable investment options ",
        " sustainable investments ",
        " emerging markets investing ",
        " crypto investment portfolio ",
        " cryptocurrency portfolio ",
        " minimizing investment risk ",
        " investment risk strategies ",
        " local loans ",
        " local loans boost community growth ",
        " high-yield uk bank accounts ",
        " high yield uk bank accounts ",
        " bank accounts in 2025 ",
        " reverse mortgages what lenders do not tell you ",
        " bank accounts without a deposit ",
        " open a bank account without a deposit ",
        " cash incentives for new bank accounts ",
        " financial scams ",
        " protecting yourself against financial scams ",
        " credit card options ",
        " choosing the right credit card ",
        " joint tax filing ",
        " tax filing with expert guidance ",
        " debt consolidation ",
        " financial management for nonprofits ",
        " strategic financial management for nonprofits ",
        " dollar-cost averaging ",
        " dollar cost averaging ",
        " crypto investment ",
        " cryptocurrency investment ",
        " crypto portfolio ",
        " cryptocurrency portfolio ",
        " impact investing ",
        " sustainable investing ",
        " sustainable investment options ",
        " strategic asset allocation ",
        " personal finance strategies ",
        " wealth management strategies ",
        " reverse mortgages ",
        " hidden truth about reverse mortgages ",
        " high-yield bank accounts ",
        " high yield bank accounts ",
        " savings accounts with higher interest rates ",
        " gold bars ",
        " costco gold bars ",
        " forex trading ",
        " commodity trading ",
        " crypto tax laws ",
        " cryptocurrency tax laws ",
        " saving or paying off debt first ",
        " financial scams ",
        " financial planning feel less overwhelming ",
        " bank account offers ",
        " cash incentives for new bank accounts ",
        " open bank accounts without deposits "
    ],

    "telecom_broadband_tv": [
        " broadband ",
        " fixed wireless ",
        " wireless internet ",
        " home internet ",
        " wireless home internet ",
        " internet options ",
        " internet plans ",
        " internet service ",
        " internet providers ",
        " internet provider ",
        " cable internet ",
        " dsl internet ",
        " satellite internet ",
        " telecom ",
        " mobile plans ",
        " family cell phone plans ",
        " 5g internet ",
        " 5g wireless ",
        " data caps ",
        " wi-fi ",
        " wifi ",
        " wi fi ",
        " portable wifi ",
        " portable wi-fi ",
        " sky tv ",
        " tv packages ",
        " streaming ",
        " smart speaker ",
        " government phones ",
        " lifeline program ",
        " free phones ",
        " iphone deals ",
        " phone deals ",
        " cell phone deals "
        " cell ",
        " phone ",
        " mobile ",
        " cellular ",
        " starlink internet ",
        " starlink package ",
        " ipv6 in telecommunications ",
        " gaming internet ",
        " internet speed for gaming ",
        " gaming setup internet ",
        " wireless earbuds ",
        " bluetooth earbuds ",
        " smartphones nearby ",
        " iphone trade-in values ",
        " cloud gaming ",
        " rise of cloud gaming ",
        " internet speed for your gaming setup ",
        " gaming setup internet speed ",
        " voip guide ",
        " voice over internet protocol ",
        " ai in network optimization ",
        " wireless internet for gamers ",
        " best writing tablets ",
        " gaming laptop guide ",
        " smartwatch features and considerations ",
        " iphone 17 deals ",
        " iphone 17 trade-in values ",
        " portable air conditioner options ",
        " no-install air conditioners ",
        " coffee makers transforming morning routines ",
        " next-gen coffee makers ",
        " wireless earbuds features ",
        " internet speed for gaming setup ",
        " smart home systems ",
        " home safety tech for families ",
        " drones under $100 ",
        " beginner drones under $100 "
    ],

    "b2b_software": [
        " software ",
        " saas ",
        " platform ",
        " cloud service ",
        " business software ",
        " enterprise software ",
        " b2b software ",
        " crm ",
        " crm software ",
        " erp ",
        " erp software ",
        " hris ",
        " hr software ",
        " hrm software ",
        " accounting software ",
        " bookkeeping software ",
        " payroll software ",
        " billing software ",
        " invoicing software ",
        " marketing software ",
        " marketing automation ",
        " email marketing software ",
        " email marketing ",
        " email marketing tools ",
        " lead generation software ",
        " lead generation ",
        " sales software ",
        " sales engagement ",
        " sales enablement ",
        " campaign metrics ",
        " call center software ",
        " contact center software ",
        " voip software ",
        " webinar software ",
        " webinar platform ",
        " observability platform ",
        " log management ",
        " backup software ",
        " disaster recovery software ",
        " cloud storage ",
        " cloud storage services ",
        " cloud data backup ",
        " cloud backup ",
        " document storage ",
        " online document storage ",
        " business cloud storage ",
        " data management ",
        " gdpr compliance software ",
        " compliance software ",
        " grc software ",
        " ad blocker ",
        " online payment systems ",
        " document management software ",
        " esignature software ",
        " e-signature software ",
        " online fax service ",
        " fax service online ",
        " help desk software ",
        " ticketing software ",
        " customer support software ",
        " service desk software ",
        " workflow automation ",
        " digital workflow automation ",
        " automation tools ",
        " ai automation tools ",
        " scheduling systems ",
        " time management tools ",
        " bpo accounting ",
        " bpo services ",
        " outsourcing services ",
        " outsourcing options ",
        " cloud solutions ",
        " local cloud ",
        " cloud migration ",
        " data security ",
        " local data security ",
        " security monitoring ",
        " security monitoring services ",
        " credit card processing ",
        " payment processing ",
        " online payment system ",
        " risk management ",
        " project management ",
        " supplier metrics ",
        " automation transforms ",
        " business automation ",
        " marketing impact ",
        " advanced targeting ",
        " call centers ",
        " call center services ",
        " consulting business ",
        " business consulting ",
        " compliance consultants ",
        " compliance solutions "
        " tech ",
        " startup ",
        " social entrepreneurship ",
        " serviced business center ",
        " serviced business centre ",
        " business center services ",
        " business centre services ",
        " business loans for small enterprises ",
        " business loans for growth ",
        " small business funding ",
        " business funding ",
        " business funding when traditional banks say no ",
        " hr courses ",
        " hr training courses ",
        " digital marketing courses ",
        " learn digital marketing ",
        " streamlining business growth ",
        " corporate ecosystems ",
        " crisis management in business ",
        " business crisis management ",
        " outsourcing boosts business efficiency ",
        " outsource it ",
        " it outsourcing ",
        " business registration services ",
        " business compliance solutions ",
        " compliance solutions ",
        " business education paths ",
        " affordable business education ",
        " digital marketing ",
        " digital marketing training ",
        " digital marketing courses ",
        " online digital marketing course ",
        " learn digital marketing ",
        " business growth technology ",
        " streamlining business operations with technology ",
        " streamlining business growth ",
        " industry 4.0 ",
        " industry 4.0 strategies ",
        " corporate ecosystems ",
        " virtual offices ",
        " virtual office services ",
        " web design firms ",
        " leading web design firms ",
        " ai tools boost workplace productivity ",
        " boost online visibility with ai tools ",
        " strengthen your online presence with content "
    ],

    "b2b_industrial": [
        " industrial machines ",
        " industrial ",
        " logistics ",
        " warehouse ",
        " warehouse picking ",
        " warehouse sale ",
        " equipment operator ",
        " forklift operator ",
        " welding programs ",
        " industrial training ",
        " laser welding ",
        " portable laser welding ",
        " food packing ",
        " food processing equipment ",
        " packaging & logistics ",
        " waste management ",
        " manufacturing efficiency ",
        " smart factories ",
        " industry 4.0 ",
        " maintenance strategies ",
        " supply chain ",
        " field service tools ",
        " field service ",
        " fleet solutions ",
        " fleet management ",
        " power generators ",
        " industrial generators ",
        " power systems ",
        " construction services ",
        " construction experts ",
        " security field careers ",
        " security guard jobs ",
        " attendance systems ",
        " workforce efficiency ",
        " ecommerce website development ",
        " online product advertising ",
        " content marketing ",
        " inventory management ",
        " advertising tools ",
        " ai tools for visibility ",
        " network security ",
        " cybersecurity ",
        " managed it support ",
        " ac repair business ",
        " hvac maintenance contracts ",
        " dashboard creation ",
        " data analytics ",
        " transportation systems ",
        " transportation logistics ",
        " complex transportation ",
        " diesel technology ",
        " diesel engines ",
        " cargo trailers ",
        " used cargo trailers ",
        " used engines ",
        " floor scrubber machines ",
        " industrial scrubbers ",
        " industrial cleaning equipment ",
        " storage rack ",
        " storage racks ",
        " warehouse racks ",
        " metal cutters ",
        " commercial ventilation ",
        " building ventilation ",
        " commercial generators ",
        " power generators ",
        " backup power options ",
        " complex transportation systems ",
        " business transportation systems ",
        " robot mowers ",
        " robotic mowers ",
        " automation leads ",
        " industrial crisis management ",
        " industry 4.0 strategies ",
        " business operations with technology ",
        " streamlining business operations with technology ",
        " specialized accounting for nonprofits ",
        " nonprofit accounting ",
        " accounting can empower nonprofits ",
        " bookkeeping matters for business growth ",
        " bookkeeping for small business ",
        " financial management for nonprofits ",
        " strategic financial management for nonprofits ",
        " outsourcing boosts business efficiency ",
        " business efficiency outsourcing ",
        " outsource accounting ",
        " accountant services ",
        " find more accountant services ",
        " business compliance remedies ",
        " tax evasion remedies ",
        " business loans for small enterprises ",
        " business loans for growth ",
        " financial management for growth ",
        " payroll management tools ",
        " dental practice management tools "
    ],

    "travel_tourism": [
        " vacation ",
        " vacations ",
        " all inclusive vacation ",
        " all inclusive vacations ",
        " all inclusive resort ",
        " resort ",
        " resorts ",
        " vacation packages ",
        " getaway ",
        " travel deals ",
        " budget travel ",
        " travel tips ",
        " travel guides ",
        " travel ideas ",
        " visiting ",
        " travel ",
        " trip "
        " cruise ",
        " cruises ",
        " cruise deals ",
        " cruise adventures ",
        " alaskan cruises ",
        " alaska cruises ",
        " msc cruises ",
        " mediterranean cruises ",
        " yacht rental ",
        " used boat ",
        " buying a used boat ",
        " private jet ",
        " villas ",
        " jacuzzis ",
        " spa retreat ",
        " luxury train ",
        " wine train ",
        " train trips ",
        " scenic train ",
        " safari ",
        " safaris ",
        " golf vacation ",
        " honeymoon ",
        " cabins ",
        " lodges ",
        " wellness retreat ",
        " national parks ",
        " wildlife tours ",
        " northern lights ",
        " destinations ",
        " bucket list travel ",
        " glamping ",
        " themed hotels ",
        " castle stay ",
        " digital nomads ",
        " slow travel ",
        " travel insurance ",
        " flights ",
        " booking flights ",
        " senior travel ",
        " cuisine ",
        " tourism ",
        " booking ",
        " tour ",
        " tours ",
        " scenic ",
        " culinary ",
        " last-minute senior cruise discounts ",
        " senior cruise discounts ",
        " cruise lines for budget travelers ",
        " memorable cruise and flight adventures ",
        " canada in 14 days ",
        " budget-friendly autumn getaways ",
        " thanksgiving dinners delivered ",
        " thanksgiving meals to go ",
        " jacuzzi hotel suites ",
        " villas stay ",
        " luxury villa stay ",
        " uncharted island adventures ",
        " roadside attractions ",
        " local festivals to check out ",
        " must-visit historical landmarks ",
        " adventure activities for adrenaline junkies ",
        " accommodations around the globe ",
        " cultural delights in europe ",
        " natural and cultural wonders of lanzarote ",
        " best local festivals ",
        " rise of the airship industry ",
        " cruise and flight adventures ",
        " budget airlines guide ",
        " golf courses offering veteran rates ",
        " public golf courses veteran rates ",
        " multi-country trip around local festivals ",
        " hostel vs guesthouse ",
        " must-visit historical landmarks ",
        " bucket list travel adventures ",
        " eastern europe walk through the heart ",
        " biodiversity treasure trove rainforest ",
        " unique date night ideas at local theater "
    ],

    "education_career": [
        " degree ",
        " online degree ",
        " online degrees ",
        " mba ",
        " master's ",
        " masters ",
        " doctorate ",
        " doctoral ",
        " phd ",
        " online phd ",
        " career ",
        " online doctorate ",
        " college ",
        " colleges ",
        " universities ",
        " campus ",
        " high school diploma ",
        " online high school ",
        " homeschool high school ",
        " online english course ",
        " learn english online ",
        " nursing programs ",
        " nursing degrees ",
        " nursing degree ",
        " online nursing ",
        " accelerated nursing ",
        " lpn programs ",
        " lpn certification ",
        " cna programs ",
        " cna certification ",
        " caregiver careers ",
        " electrical engineering degree ",
        " civil engineering degree ",
        " computer science courses ",
        " stem courses ",
        " vocational training ",
        " electrician courses ",
        " electrician training ",
        " welding programs ",
        " coding bootcamp ",
        " coding bootcamps ",
        " game development degrees ",
        " yoga teaching certification ",
        " graphic design courses ",
        " veterinary assistant ",
        " anatomy knowledge ",
        " scholarships ",
        " mba scholarships ",
        " tuition assistance ",
        " military tuition assistance ",
        " cdl training ",
        " trucking career ",
        " aviation training ",
        " aviation mechanics ",
        " security field careers ",
        " warehouse careers ",
        " moving industry careers ",
        " restaurant industry careers ",
        " laundry industry careers ",
        " online learning ",
        " hybrid learning ",
        " career development ",
        " career mentorship ",
        " skill based learning ",
        " security guard training "
        " hr courses ",
        " hr training ",
        " digital marketing courses ",
        " learn digital marketing ",
        " online accounting degrees ",
        " accounting degrees ",
        " physical therapy education ",
        " physical therapy programs ",
        " nursing degrees ",
        " accelerated online programs ",
        " english speaking courses ",
        " hospitality industry careers ",
        " precision agriculture course ",
        " online phds ",
        " free online phds ",
        " christian k12 online schools ",
        " study abroad ",
        " master’s in child development ",
        " counseling programs ",
        " psychology programs ",
        " influencer agency ",
        " restaurant industry careers ",
        " professional certifications ",
        " graduate degrees for mature students ",
        " study groups benefits ",
        " online vs traditional degrees ",
        " professional certifications ",
        " gmat gre guide ",
        " networking job opportunities ",
        " platforms for learning new skills ",
        " resume that will help you land a job abroad ",
        " state-funded tuition options ",
        " dietary and nutrition education ",
        " cosmetology education guide ",
        " affordable business education paths ",
        " online tutoring services ",
        " top online tutoring services ",
        " visa lottery 2025 ",
        " u.s. visa lottery 2025 ",
        " early childhood education programs ",
        " commercial driving beginner’s guide ",
        " get certified in addiction counseling ",
        " lpn bridge programs ",
        " nursing courses with free laptops ",
        " master’s in child development online ",
        " state-funded tuition options ",
        " professional development ",
        " fully funded master’s programs ",
        " ai and machine learning courses ",
        " physical therapy program paths ",
        " physical therapy education paths ",
        " nursing courses with free laptops ",
        " free laptops in nursing courses ",
        " early childhood education programs ",
        " online tutoring services ",
        " top online tutoring services ",
        " mechanical engineer training ",
        " find more mechanical engineer training ",
        " commercial driving beginner’s guide ",
        " army aptitude test ",
        " state-funded tuition options ",
        " fully funded master’s programs ",
        " fully funded psychology programs ",
        " master’s in child development online ",
        " restaurant industry roles ",
        " spanish educator guide ",
        " in-person vs online doctorates ",
        " ai and machine learning courses ",
        " online training platforms ",
        " online lpn courses ",
        " dental assistant training options ",
        " dental assistant programs ",
        " licensing exam success strategies ",
        " inclusive campuses for neurodivergent students ",
        " diversity and inclusion in higher education ",
        " professional development tools ",
        " mind mapping tools for strategic thinking ",
        " smart note-taking apps ",
        " virtual whiteboard tools ",
        " digital portfolio with canva ",
        " time management strategies for remote workers "
    ],

    "fashion_beauty": [
        " dresses ",
        " maxi dresses ",
        " a-line dresses ",
        " sheath dresses ",
        " bohemian dresses ",
        " boho dresses ",
        " outfits for women ",
        " mature women ",
        " mature women style ",
        " older women style ",
        " comfortable pants ",
        " pull-on pants ",
        " long sleeve tees ",
        " outfit ",
        " wardrobe ",
        " micro bikini ",
        " bikini styles ",
        " daring bikini ",
        " lingerie ",
        " underwear ",
        " nighties ",
        " underwear sets ",
        " lingerie sets ",
        " nightwear ",
        " thong ",
        " thongs ",
        " g string ",
        " g strings ",
        " g-string ",
        " g-strings ",
        " silk sleepwear ",
        " silk bras ",
        " intimate apparel ",
        " shapewear ",
        " bras ",
        " full-coverage bras ",
        " slides ",
        " high heels ",
        " shoes ",
        " hair transplant ",
        " hair volume ",
        " thinning hair ",
        " hairstyles ",
        " hair loss ",
        " hair color ",
        " rhinoplasty ",
        " anti-aging cream ",
        " anti aging cream ",
        " anti aging ",
        " anti-ageing ",
        " skincare ",
        " skin care ",
        " skincare routine ",
        " skin care routine ",
        " eye creams ",
        " niacinamide ",
        " summer glow ",
        " nail art ",
        " makeup ",
        " beauty standards ",
        " beauty ",
        " wigs ",
        " hairpieces ",
        " wiglets ",
        " fashion "
        " handbag ",
        " handbags ",
        " purse ",
        " purses ",
        " tote ",
        " style ",
        " designer clothes inventory ",
        " designer clothes sales ",
        " men’s swimwear trends ",
        " mens swimwear trends ",
        " women’s sleepwear ",
        " breathable sleepwear ",
        " front-opening sleepwear ",
        " techwear ",
        " streetwear ",
        " high heel trends ",
        " high heel ",
        " lab-grown diamonds ",
        " hair transplantation ",
        " belly fat removal ",
        " non-surgical facelift ",
        " superfoods for skin ",
        " radiant skin ",
        " men’s grooming ",
        " modern men’s grooming ",
        " furniture finds at thrift stores ",
        " pre-loved fashion ",
        " pre loved fashion ",
        " mature woman fashion ",
        " stylish mature woman ",
        " mother of the bride trends ",
        " mother and grandmother of the bride ",
        " classy and casual women’s clothes ",
        " women hair salons ",
        " best salons near you ",
        " men’s grooming across europe ",
        " modern men’s grooming ",
        " men’s swimwear trends ",
        " dip-dye ",
        " fresh take on color in fashion ",
        " gender-neutral fashion ",
        " new masculine grooming ",
        " foundation for your skin type ",
        " designer jewelry deals ",
        " chic alternatives to jeans ",
        " sandals with arch support ",
        " women’s front-opening breathable sleepwear ",
        " sophisticated women's necklaces ",
        " hair solutions for older women ",
        " fashionable mature woman ",
        " terracotta revival in homes ",
        " shabby chic ",
        " cottagecore ",
        " mediterranean-inspired interiors ",
        " men’s swimwear trends ",
        " bold cuts colors minimal styles ",
        " men’s grooming across europe ",
        " modern men’s grooming ",
        " locally-made soaps and balms ",
        " artisan soaps and balms ",
        " gender-neutral fashion ",
        " dark academia fashion ",
        " artisanal fashion techniques ",
        " mature woman fashion guide ",
        " sophisticated mature woman fashion ",
        " a-line edition clothes for ladies ",
        " mother of the bride fashion ",
        " women’s necklaces ",
        " hair solutions for refined older women ",
        " dermal fillers enhance youthful looks ",
        " eyebrow restoration natural results ",
        " flattering swimwear every body shape "
    ],

    "zodiac_astrology": [
        # Core zodiac / horoscope terms
        " zodiac sign ",
        " zodiac signs ",
        " zodiac ",
        " star sign ",
        " star signs ",
        " horoscope ",
        " brunch horoscope ",
        " astrology ",
        " astrology memes ",
        " astrological ",
        " sign’s money personality ",
        " money personality ",
        " your sign ",
        " sign’s signature flaw ",
        " where you should live based on personality ",
        " your sign’s money personality ",
        " your sign’s signature flaw ",
        " where you should live in the usa based on your personality ",
        " predictions that tell us what our future could look like "
    ],

    "law_legal": [
        " lawyer ",
        " lawyers ",
        " attorney ",
        " attorneys ",
        " law firm ",
        " law firms ",
        " law office ",
        " law offices ",
        " legal help ",
        " legal advice ",
        " legal services ",
        " legal representation ",
        " legal assistance ",
        " legal aid ",
        " pro bono services ",
        " lawsuit ",
        " lawsuits ",
        " settlement ",
        " settlements ",
        " class action ",
        " compensation claim ",
        " compensation claims ",
        " injury claim ",
        " injury claims ",
        " slip and fall ",
        " slip and fall lawsuits ",
        " personal injury ",
        " maximize personal injury compensation ",
        " civil forfeiture ",
        " eminent domain ",
        " dui charges ",
        " divorce online ",
        " divorce lawyers ",
        " affordable divorce ",
        " construction accident lawyers ",
        " construction injury ",
        " texas injury claims ",
        " legal expenses insurance ",
        " accident insurance ",
        " cryptocurrency regulations ",
        " sovereign immunity ",
        " tax evasion remedies ",
        " workers’ compensation in the usa ",
        " workers compensation legal support ",
        " divorce and family disputes ",
        " professional legal support for divorce ",
        " corporate tax evasion legal remedies ",
        " construction site injury rights ",
        " maritime accidents key details ",
        " reverse mortgages what lenders don't tell you ",
        " us citizenship test ",
        " judicial activism analytical overview "
    ],

    "pets_animals": [
        " french bulldogs ",
        " chihuahua puppies ",
        " chihuahua puppy ",
        " small dogs ",
        " dogs ",
        " dog care ",
        " pet care ",
        " kennel ",
        " outdoor kennels ",
        " dog insurance ",
        " pet insurance ",
        " pet supplies ",
        " pet stores ",
        " pet supply stores ",
        " leafcutter ants ",
        " australian quokka ",
        " wildlife destinations "
    ],

    "funeral_cremation": [
        " cremation ",
        " cremation costs ",
        " cremation cost ",
        " direct cremation ",
        " funeral insurance ",
        " cremation services ",
        " cremation process ",
        " cremation expenses ",
        " funeral service costs ",
        " funeral services ",
        " ashes handling "
    ],

    "dating_relationships": [
        " dating ",
        " finding love ",
        " singles ",
        " relationships ",
        " love after 50 ",
        " love after 60 ",
        " speed dating ",
        " citas rápidas ",
        " online dating ",
        " zodiac sign loves ",
        " how your sign loves "
    ],

    "entertainment_popculture": [
        " memes ",
        " netflix ",
        " horror movies ",
        " trivia games ",
        " metaverse concerts ",
        " hollywood ",
        " celebrity ",
        " red carpet ",
        " broadway ",
        " movie trailers ",
        " blockbusters ",
        " esports ",
        " gaming titles ",
        " video game soundtracks ",
        " interactive theater ",
        " live performances "
        " cloud gaming ",
        " vr theater ",
        " virtual reality in film ",
        " indie games ",
        " indie films ",
        " emerging indie films ",
        " animated movies ",
        " top sci-fi series ",
        " comedy movies ",
        " tv show cliffhangers ",
        " best albums ",
        " albums 2024 ",
        " must-listen podcasts ",
        " anticipated tv shows ",
        " entertainment online ",
        " theater today ",
        " 3d audio ",
        " emojis language ",
        " meme culture ",
        " popular culture ",
        " cloud gaming revolutionary leap ",
        " vr in the film industry ",
        " virtual reality in live performances ",
        " pixelated politics ",
        " gaming shapes sociopolitical discourse ",
        " indie films that made a fortune ",
        " top sci-fi series ",
        " must-see comedy movies ",
        " animated movies making waves ",
        " top grossing films of 2024 ",
        " best albums of 2024 ",
        " must-listen podcasts ",
        " entertainment online guide "
    ],

    "general_lifestyle": [
        " decluttering ",
        " hygge ",
        " cozy home ",
        " diy projects ",
        " mason jars ",
        " home office space ",
        " wardrobe ",
        " minimalism ",
        " digital decluttering ",
        " mindfulness in everyday life ",
        " balanced lifestyle ",
        " mental well-being ",
        " tiny habits ",
        " impulse spending traps ",
        " cold showers ",
        " blue light glasses ",
        " sleep habits ",
        " lazy person’s guide ",
        " clean home guide ",
        " screen time ",
        " eco-friendly living ",
        " sustainable traveler ",
        " eco-friendly practices ",
        " forest bathing ",
        " slow living ",
        " conscious consumption ",
        " tiny habits that could save you hundreds ",
        " impulse spending traps ",
        " money-saving myths ",
        " lazy person’s guide to keeping a clean home ",
        " outdoor upgrades that make your backyard feel luxe ",
        " power of paint one wall one weekend ",
        " psychology tips for social anxiety ",
        " reduce your stress at work ",
        " feeling stressed try these tips ",
        " overcoming the coronavirus blues ",
        " seasonal shopping trends ",
        " smart shopping tips for the season ",
        " thanksgiving meal delivery ",
        " thanksgiving meals to go ",
        " thanksgiving dinners delivered ",
        " italian christmas appetizers ",
        " christmas appetizers ",
        " make ahead christmas side dishes ",
        " spooky halloween appetizers ",
        " christmas gadgets ",
        " black friday event 2025 ",
        " macy's black friday ",
        " walmart black friday ",
        " tesco's black friday ",
        " veterans day deals ",
        " cyber monday sale ",
        " prime day success ",
        " seasonal shopping tips ",
        " online shopping deals for clothes ",
        " furniture clearance deals ",
        " kitchen and bath cabinet deals ",
        " coupon websites for unmatched deals ",
        " free iphone 14 guide ",
        " walmart phones for sale ",
        " oakley safety sunglasses ",
        " oakley gear ",
        " oakley assault boots ",
        " prime day deals ",
        " cyber monday sale ",
        " laptop discounts ",
        " affordable designer jewelry deals ",
        " unsold couches and sofas ",
        " police auction jewelry ",
        " police seized cars ",
        " coches incautados por la policia ",
        " skiing basics ",
        " ski holidays planning tips ",
        " tennis serve biomechanics ",
        " tennis biomechanics analysis ",
        " bowling delivery in cricket ",
        " futsal intricacies ",
        " mixed martial arts rise ",
        " public golf courses ",
        " horseback riding basics ",
        " smart home basics ",
        " enjoy your outdoor space as temperatures drop ",
        " organize and use outdoor storage spaces ",
        " home gym equipment must-have ",
        " outdoor lighting ideas ",
        " stylish storage solutions ",
        " lazy person’s guide to keeping a clean home ",
        " tiny habits that could save you hundreds ",
        " impulse spending traps ",
        " money-saving myths ",
        " step-by-step guide removing all the dust in your home ",
        " vinegar drain unblock ",
        " diy dishwasher detergent ",
        " oatmeal more tasty ",
        " limiting your teen's screen time ",
        " help kids resist peer pressure ",
        " ethical choices for kids ",
        " hobbies for rainy days ",
        " book clubs for avid readers ",
        " gardening workshops ",
        " fake news prevention strategies ",
        " safe browsing habits ",
        " safe driving tips for new drivers ",
        " getting involved in local politics ",
        " community development equality ",
        " conscious consumption shift ",
        " slow living movement ",
        " forest bathing trend "
        ],

        "home_services": [
        " cleaning service guide ",
        " right cleaning services ",
        " best cleaning services ",
        " cleaning and restoration ",
        " fall home maintenance guide ",
        " home maintenance guide ",
        " envelope stuffing jobs ",
        " envelope stuffing claims ",
        " home heating systems 2025 ",
        " house heating systems ",
        " gas generator services ",
        " generators for home use ",
        " reliable power solutions ",
        " gutter maintenance tips ",
        " local roof repairs ",
        " local roofers ",
        " asphalt paving contractors ",
        " tree clearing companies ",
        " tree care services ",
        " vent cleaning ",
        " concrete crack repair ",
        " pressure cleaning services ",
        " power washing ",
        " soundproofing your room ",
        " pest prevention tips for homeowners ",
        " cockroaches safely and quickly ",
        " bed bugs management ",
        " yard free of moles ",
        " hvac ",
        " air conditioning ",
        " ac repair ",
        " furnace repair ",
        " heating repair ",
        " boiler repair ",
        " heater installation ",
        " heater replacement ",
        " plumbing ",
        " plumbing services ",
        " plumbing service ",
        " plumber ",
        " plumbers ",
        " drain cleaning ",
        " clogged drain ",
        " sewer line ",
        " septic tank ",
        " leak repair ",
        " water leak ",
        " pipe repair ",
        " burst pipe ",
        " water heater ",
        " water heater repair ",
        " tankless water heater ",
        " electrician ",
        " electrical services ",
        " electrical repair ",
        " rewiring ",
        " panel upgrade ",
        " generator installation ",
        " generator installer ",
        " roof repair ",
        " roofing ",
        " roofing contractors ",
        " roofing contractor ",
        " roof replacement ",
        " roof leak ",
        " roof leaks ",
        " gutter cleaning ",
        " gutter repair ",
        " siding repair ",
        " window replacement ",
        " replacement windows ",
        " door installation ",
        " garage door repair ",
        " garage door service ",
        " insulation ",
        " attic insulation ",
        " spray foam insulation ",
        " mold removal ",
        " mold remediation ",
        " water damage ",
        " fire damage restoration ",
        " flood cleanup ",
        " pest control ",
        " termite treatment ",
        " bed bug removal ",
        " rodent control ",
        " lawn care ",
        " landscaping ",
        " tree removal ",
        " tree services ",
        " tree service ",
        " tree trimming ",
        " stump removal ",
        " house cleaning ",
        " home cleaning ",
        " maid service ",
        " deep cleaning ",
        " carpet cleaning ",
        " tile and grout cleaning ",
        " bathroom remodeling ",
        " kitchen remodeling ",
        " home remodeling ",
        " home renovation ",
        " home repair ",
        " remodeling contractors ",
        " home inspection ",
        " handyman services "
        " home & garden ",
        " home garden ",
        " garden studios ",
        " garden studio ",
        " wildlife-friendly garden ",
        " wildlife friendly garden ",
        " garden umbrellas ",
        " garden umbrella ",
        " lavender in your garden ",
        " home garden tips ",
        " planning a successful home garden ",
        " wildlife-friendly ",
        " patio crack repairs ",
        " garden fence types ",
        " garden fence costs "
        " maid cleaning costs ",
        " maid cleaning ",
        " maid services ",
        " affordable cleaning services ",
        " housekeeping services ",
        " mattress delivery ",
        " mattress delivery services ",
        " patio concrete crack ",
        " concrete crack repair ",
        " concrete cracks ",
        " roof waterproofing ",
        " roof waterproofing guide ",
        " air sealing contractors ",
        " air sealing ",
        " metal roofs ",
        " metal roof ",
        " soundproofing your room ",
        " soundproofing room ",
        " pressure cleaning ",
        " pressure cleaning services ",
        " vent cleaning ",
        " home security systems ",
        " home security system ",
        " alarm systems work at home ",
        " tree care ",
        " professional tree care ",
        " tree cutting services ",
        " tree cutting ",
        " local roof repairs ",
        " local roofers ",
        " roof repairs ",
        " pool contractors ",
        " swimming pool contractors ",
        " plunge pool ",
        " home emergency generators ",
        " water boiler replacement ",
        " interior surface damage ",
        " interior damage repair ",
        " moving companies ",
        " moving company ",
        " home gym equipment ",
        " home gym design ",
        " garage organization ",
        " simple home repairs ",
        " leaky faucet ",
        " refinishing wood ",
        " single family rental ",
        " single-family rental ",
        " rental investments ",
        " commercial real estate ",
        " off-market real estate ",
        " off market real estate ",
        " real estate wholesaling ",
        " real estate listings ",
        " local real estate listings ",
        " unsold couches ",
        " unsold sofas ",
        " second hand sofas ",
        " tiny homes ",
        " tiny home ",
        " container houses ",
        " container houses 2025 ",
        " 2-bed senior houses ",
        " senior residences ",
        " senior cottages ",
        " home market value ",
        " approximate value of your home ",
        " best garden fence ",
        " garden fence for your needs ",
        " multifunctional spaces ",
        " future of home and garden design ",
        " home & garden design ",
        " outdoor space as the temperatures drop ",
        " baking soda uses in your garden ",
        " planning a successful home garden ",
        " wildlife-friendly garden ",
        " lavender in your garden ",
        " garden fence types costs installation ",
        " backyard feel luxe ",
        " outdoor upgrades ",
        " outdoor pool options ",
        " backyard pool innovations ",
        " lawn weed-free ",
        " yard free of moles ",
        " wasp traps ",
        " diy wasp traps ",
        " modern window trends ",
        " window treatments for stylish homes ",
        " fixing damaged windows ",
        " automatic window shades ",
        " blackout roller blinds ",
        " home decoration space utilization ",
        " exclusive living aesthetics ",
        " kitchen renovation ideas ",
        " kitchen deals trends and functionality ",
        " trending kitchen cabinet colors ",
        " backyard pool innovations ",
        " backyard summer oasis ",
        " faux stone panels ",
        " wood wall panels ",
        " monochrome home decor ",
        " terracotta revival in modern homes ",
        " wabi-sabi home decor ",
        " mosaic art in modern home decor ",
        " cottagecore home spaces ",
        " shabby chic ",
        " multi-functional furniture ",
        " modular seating ",
        " home gym design ",
        " rubber coated floors in garages ",
        " garage floor coatings ",
        " ductless ac units ",
        " unsold kitchens ",
        " barndominium costs and designs ",
        " quonset huts for sale "
    ],

    "travel_destinations": [
        " caribbean ",
        " maldives ",
        " seychelles ",
        " bali ",
        " phuket ",
        " bora bora ",
        " tahiti ",
        " fiji ",
        " hawaii ",
        " maui ",
        " oahu ",
        " kauai ",
        " santorini ",
        " mykonos ",
        " greek islands ",
        " italy ",
        " amalfi coast ",
        " tuscany ",
        " rome ",
        " venice ",
        " florence ",
        " milan ",
        " france ",
        " paris ",
        " french riviera ",
        " cote d azur ",
        " spain ",
        " barcelona ",
        " madrid ",
        " seville ",
        " ibiza ",
        " portugal ",
        " lisbon ",
        " algarve ",
        " dubai ",
        " abu dhabi ",
        " united arab emirates ",
        " uae ",
        " turkey ",
        " antalya ",
        " alanya ",
        " turkish riviera ",
        " croatia ",
        " dubrovnik ",
        " split ",
        " italy vacation ",
        " europe tour ",
        " european cities ",
        " london ",
        " edinburgh ",
        " scotland ",
        " ireland ",
        " dublin ",
        " switzerland ",
        " zurich ",
        " geneva ",
        " swiss alps ",
        " norway ",
        " fjords ",
        " norway fjords ",
        " iceland ",
        " japan ",
        " tokyo ",
        " kyoto ",
        " osaka ",
        " china ",
        " beijing ",
        " shanghai ",
        " hong kong ",
        " singapore ",
        " thailand ",
        " bangkok ",
        " chiang mai ",
        " vietnam ",
        " bali resort ",
        " beach resort ",
        " island getaway ",
        " all inclusive resort ",
        " all inclusive vacation ",
        " caribbean cruise ",
        " alaska cruise ",
        " alaskan cruise ",
        " mediterranean cruise ",
        " european river cruise ",
        " safari ",
        " african safari ",
        " kenya safari ",
        " tanzania safari ",
        " south africa safari ",
        " canada road trip ",
        " usa road trip ",
        " national parks ",
        " yellowstone ",
        " yosemite ",
        " grand canyon ",
        " alaska vacation ",
        " wine tours ",
        " wine train ",
        " luxury train ",
        " scenic train ",
        " business class tickets ",
        " business class flights ",
        " affordable business class ",
        " jacuzzi hotel suites ",
        " jacuzzi suites ",
        " hidden food gems ",
        " food gems ",
        " summer camps ",
        " summer camp ",
        " train adventure ",
        " train adventures ",
        " globetrotting train ",
        " autumn getaways ",
        " budget airlines ",
        " budget airlines guide ",
        " global entry ",
        " tsa pre-check ",
        " tsa precheck ",
        " clear membership ",
        " hot springs and spas ",
        " natural hot springs ",
        " spa resorts ",
        " assateague island ",
        " assateague island state park ",
        " sedona activities ",
        " branson missouri ",
        " historic battlefields ",
        " himalayas ",
        " tourist attractions across the states ",
        " cultural festivals ",
        " must-visit historical landmarks ",
        " sleeper trains ",
        " sleeper train comeback "
    ],


}

def normalize(text: str) -> str:
    text = text.lower()
    # Replace anything that's not a-z or 0-9 with a space
    text = re.sub(r"[^a-z0-9]+", " ", text)
    # Collapse multiple spaces
    text = re.sub(r"\s+", " ", text).strip()
    # Pad with spaces so " car " style patterns still work
    return f" {text} "

def classify(headline: str) -> str:
    text = normalize(headline)
    for niche, patterns in RULES.items():
        for pat in patterns:
            # patterns are already lowercased; most have leading/trailing spaces
            if pat in text:
                return niche
    return "unknown"

with open(INPUT, newline="", encoding="utf-8") as f_in, \
     open(OUTPUT, "w", newline="", encoding="utf-8") as f_out:
    reader = csv.DictReader(f_in)
    fieldnames = ["headline", "niche"]
    writer = csv.DictWriter(f_out, fieldnames=fieldnames)
    writer.writeheader()
    for row in reader:
        h = row["headline"]
        niche = classify(h)
        writer.writerow({"headline": h, "niche": niche})

# After you’ve generated headlines_with_niches.csv
unknowns = []
with open(OUTPUT, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        if row["niche"] == "unknown":
            unknowns.append(row["headline"])

# Write unknowns out for review
with open("headlines_unknown.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["headline"])
    for h in unknowns:
        writer.writerow([h])        